name: poetry install
description: poetry install
inputs:
  virtualenvs-create:
    description: Create (or not) virtualenvs
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # TODO? move to self_add_plugins ?
    - name: poetry config virtualenvs.create
      shell: bash
      run: poetry config virtualenvs.create ${{ inputs.virtualenvs-create }}

    - name: poetry install
      shell: bash
      run: poetry install
