name: poetry install
description: poetry install

inputs:
  virtualenvs-create:
    description: Create (or not) virtualenvs
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: percebus/github-actions-poetry/.github/actions/config_virtualenvs_create@main
      with:
        virtualenvs-create: ${{ inputs.virtualenvs-create }}

    - name: poetry install
      shell: bash
      run: poetry install
