name: poetry self add plugins
description: Add plugins from a requirements.txt file
inputs:
  requirements-file:
    description: Path to the requirements file
    required: false
    default: ./requirements.poetry-plugin.txt

  virtualenvs-create:
    description: Create (or not) virtualenvs
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # TODO
    # - uses: percebus/github-actions-poetry/.github/actions/config_virtualenvs_create@main
    #   with:
    #     virtualenvs-create: ${{ inputs.virtualenvs-create }}

    - name: cat ${{ inputs.requirements-file }}
      shell: bash
      run: cat ${{ inputs.requirements-file }}

    - name: poetry self add
      shell: bash
      run: cat ${{ inputs.requirements-file }} | sed 's/.*/"&"/' | xargs -n 1 poetry self add

    - name: poetry self show plugins
      shell: bash
      run: poetry self show plugins
