name: Test actions/self_add_plugins

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main
      - uses: percebus/github-actions-pipx/.github/actions/install@main
      - uses: ./.github/actions/self_add_plugins
      - uses: percebus/github-actions-pip/.github/actions/freeze@main

  python__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    name: python @ ${{ matrix.python-version }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-python/.github/actions/setup@main
        with:
          python-version: ${{ matrix.python-version }}

      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main
      - uses: percebus/github-actions-pipx/.github/actions/install@main
      - uses: ./.github/actions/self_add_plugins
      - uses: percebus/github-actions-pip/.github/actions/freeze@main

  poetry__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        poetry-version:
          - "1.x.x"
          - "2.x.x"

    name: poetry @ ${{ matrix.poetry-version }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main
      - uses: percebus/github-actions-pipx/.github/actions/install@main
        with:
          requirements-file: assets/examples/poetry/${{ matrix.poetry-version }}/requirements.pipx.txt

      - uses: ./.github/actions/self_add_plugins
        with:
          requirements-file: assets/examples/poetry/${{ matrix.poetry-version }}/requirements.poetry-plugin.txt

      - uses: percebus/github-actions-pip/.github/actions/freeze@main

  requirements__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - poetry-plugin-export
          - poetry-plugin-shell
          - poetry-plugin-sort
          - pip_compatible

    name: "plugins: ${{ matrix.example }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main
      - uses: percebus/github-actions-pipx/.github/actions/install@main
      - uses: ./.github/actions/self_add_plugins
        with:
          requirements-file: assets/examples/plugins/${{ matrix.example }}/requirements.poetry-plugin.txt

      - uses: percebus/github-actions-pip/.github/actions/freeze@main
